/* =========================================================
   XEQUE TOTAL — dados dos times, jogadores, temperamentos e poderes
   Tabuleiro horizontal: 13 colunas (0-12) x 9 linhas (0-8).

   GAME_DATA.TEAMS é um POOL de squads escolhíveis (não são mais
   times fixos A/B). Cada squad guarda sua formação em ORIENTAÇÃO
   CANÔNICA "esquerda" (como se sempre defendesse a coluna 0 e
   atacasse a coluna 12) — quem decide o lado real em campo (slot A
   ou B, direção de ataque, coluna do gol) é GAME.start(), na hora
   de montar a partida (ver SLOT_META em js/game.js).

   O movimento de cada jogador é definido pelo TEMPERAMENTO (exceto
   o goleiro, que sempre se move como Rei-de-xadrez/1 casa). A única
   exceção de peso: a personalidade "Rei" (exclusiva do Dadá
   Majestade) se move como uma dama sem limite de alcance.
========================================================= */

var GAME_DATA = (function () {

  var POSITIONS = {
    GK: { label: "Goleiro", short: "GOL" },
    DF: { label: "Zagueiro", short: "ZAG" },
    LAT: { label: "Lateral", short: "LAT" },
    MF: { label: "Meio-campo", short: "MEI" },
    FW: { label: "Atacante", short: "ATA" }
  };

  // define o formato de movimento de cada temperamento (o goleiro ignora isso e sempre usa "king")
  var TEMPERAMENTS = {
    "Rápido": { shape: "bishop", maxDist: 4, icon: "🏃", moveLabel: "Bispo (diagonal, até 4 casas)" },
    "Bruto": { shape: "rook", maxDist: 4, icon: "💪", moveLabel: "Torre (reta, até 4 casas)" },
    "Cerebral": { shape: "queen", maxDist: 3, icon: "🧠", moveLabel: "Dama limitada (até 3 casas)" },
    "Oportunista": { shape: "knight", maxDist: null, icon: "🎯", moveLabel: "Cavalo (salto em L)" },
    "Rei": { shape: "queen", maxDist: null, icon: "👑", moveLabel: "Dama (reta e diagonal, sem limite de alcance)" }
  };

  var STATS = {
    velocidade: "Velocidade",
    chute: "Chute",
    tecnica: "Técnica",
    defesa: "Defesa",
    espirito: "Espírito"
  };

  function player(p) {
    return {
      id: p.id, name: p.name, number: p.number,
      nationality: p.nationality, flag: p.flag,
      temperament: p.temperament, position: p.position,
      stats: p.stats,
      power: { name: p.power.name, desc: p.power.desc, manaCost: p.power.manaCost, bonus: p.power.bonus },
      start: p.start, maxMana: 100, quote: p.quote || "",
      assetKey: p.assetKey
    };
  }

  var TEAMS = [
    {
      id: "BRA", name: "Brasil", shortName: "BRA", kit: "CBF · Amarelo-Canarinho",
      colorVar: "brasil", badge: "🇧🇷", assetPrefix: "BRASIL",
      players: [
        player({ id: "bra-1", name: "Vadinho Paredão", number: 1, nationality: "Brasil", flag: "🇧🇷", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 50, chute: 10, tecnica: 48, defesa: 89, espirito: 85 },
          power: { name: "Milagre da Área", desc: "Uma defesa impossível que vira lenda instantânea.", manaCost: 46, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Bola que passa por mim paga pedágio." }),
        player({ id: "bra-2", name: "Deco Metrô", number: 2, nationality: "Brasil", flag: "🇧🇷", temperament: "Rápido", position: "LAT",
          stats: { velocidade: 90, chute: 45, tecnica: 66, defesa: 75, espirito: 78 },
          power: { name: "Sobe e Desce Infinito", desc: "Corre a lateral inteira sem perder o fôlego, ida e volta.", manaCost: 36, bonus: 29 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Eu não tenho posição fixa, eu tenho rota." }),
        player({ id: "bra-3", name: "Lucão Trator", number: 3, nationality: "Brasil", flag: "🇧🇷", temperament: "Bruto", position: "DF",
          stats: { velocidade: 72, chute: 50, tecnica: 58, defesa: 86, espirito: 75 },
          power: { name: "Cabeçada de Aço", desc: "Sobe mais alto que todo mundo e manda embora de cabeça.", manaCost: 35, bonus: 28 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Bola aérea é meu almoço." }),
        player({ id: "bra-4", name: "Osvaldo Taça-Alta", number: 4, nationality: "Brasil", flag: "🇧🇷", temperament: "Bruto", position: "DF",
          stats: { velocidade: 55, chute: 30, tecnica: 55, defesa: 84, espirito: 88 },
          power: { name: "Liderança Inabalável", desc: "Levanta o time e a marcação com a mesma força.", manaCost: 34, bonus: 27 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Capitão não recua." }),
        player({ id: "bra-5", name: "Beto Trovão", number: 5, nationality: "Brasil", flag: "🇧🇷", temperament: "Bruto", position: "LAT",
          stats: { velocidade: 87, chute: 82, tecnica: 70, defesa: 73, espirito: 72 },
          power: { name: "Chute Curva-Mundo", desc: "Um chute tão forte e curvo que desafia a física.", manaCost: 37, bonus: 29 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Se eu bater, a rede que se cuide." }),
        player({ id: "bra-6", name: "Valdomiro Folha-Seca", number: 6, nationality: "Brasil", flag: "🇧🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 58, chute: 65, tecnica: 85, defesa: 55, espirito: 80 },
          power: { name: "Folha Seca", desc: "Um chute de efeito que cai na hora certa, sem aviso.", manaCost: 40, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Vento nenhum decide onde a bola cai. Eu decido." }),
        player({ id: "bra-7", name: "Arthur Galo-de-Aço", number: 7, nationality: "Brasil", flag: "🇧🇷", temperament: "Oportunista", position: "MF",
          stats: { velocidade: 72, chute: 84, tecnica: 87, defesa: 40, espirito: 74 },
          power: { name: "Bico Certeiro", desc: "Aparece na hora exata pra cravar o gol impossível.", manaCost: 41, bonus: 31 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "Cocorocó. Foi gol." }),
        player({ id: "bra-8", name: "Renato Sabença", number: 8, nationality: "Brasil", flag: "🇧🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 60, chute: 66, tecnica: 86, defesa: 45, espirito: 85 },
          power: { name: "Diagnóstico Preciso", desc: "Lê o jogo inteiro antes de todo mundo e prescreve o passe certo.", manaCost: 41, bonus: 31 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "Chamem-me apenas de Doutor." }),
        player({ id: "bra-9", name: "Joel Zigue-Zague", number: 9, nationality: "Brasil", flag: "🇧🇷", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 85, chute: 70, tecnica: 92, defesa: 22, espirito: 68 },
          power: { name: "Requebro Impossível", desc: "Um drible tão absurdo que a marcação simplesmente desaparece.", manaCost: 48, bonus: 36 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Marcador? Nunca vi um de perto." }),
        player({ id: "bra-10", name: "Dadá Majestade", number: 10, nationality: "Brasil", flag: "🇧🇷", temperament: "Rei", position: "FW",
          stats: { velocidade: 86, chute: 90, tecnica: 95, defesa: 35, espirito: 92 },
          power: { name: "Toque de Rei", desc: "Um chute de tal categoria que até o goleiro tira o chapéu.", manaCost: 49, bonus: 37 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "Chama o Rei." }),
        player({ id: "bra-11", name: "Nando Fenômeno", number: 11, nationality: "Brasil", flag: "🇧🇷", temperament: "Rápido", position: "FW",
          stats: { velocidade: 89, chute: 88, tecnica: 84, defesa: 26, espirito: 70 },
          power: { name: "Explosão Fenomenal", desc: "Acelera de um jeito que a defesa nem processa o que aconteceu.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Fenômeno não se explica. Se assiste." })
      ]
    },
    {
      id: "ALE", name: "Alemanha", shortName: "ALE", kit: "DFB · Preto & Ouro",
      colorVar: "alemanha", badge: "🇩🇪", assetPrefix: "ALEMANHA",
      players: [
        player({ id: "ale-1", name: "Manfred Zagoleiro", number: 1, nationality: "Alemanha", flag: "🇩🇪", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 62, chute: 15, tecnica: 55, defesa: 90, espirito: 83 },
          power: { name: "Goleiro-Linha", desc: "Sai da área como um zagueiro extra e ainda assim defende tudo.", manaCost: 47, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Minha área é o campo inteiro." }),
        player({ id: "ale-2", name: "Phil Anão-Mágico", number: 2, nationality: "Alemanha", flag: "🇩🇪", temperament: "Cerebral", position: "LAT",
          stats: { velocidade: 68, chute: 40, tecnica: 78, defesa: 78, espirito: 84 },
          power: { name: "Leitura Tática", desc: "Antecipa a jogada inteira antes mesmo dela começar.", manaCost: 36, bonus: 28 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Pequeno de estatura, gigante de cabeça." }),
        player({ id: "ale-3", name: "Franzl Imperador", number: 3, nationality: "Alemanha", flag: "🇩🇪", temperament: "Cerebral", position: "DF",
          stats: { velocidade: 66, chute: 48, tecnica: 88, defesa: 82, espirito: 86 },
          power: { name: "Passe Real", desc: "Um lançamento tão preciso que parece ordem de comando.", manaCost: 35, bonus: 28 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Eu não defendo. Eu governo a zaga." }),
        player({ id: "ale-4", name: "Dieter Libero-Voador", number: 4, nationality: "Alemanha", flag: "🇩🇪", temperament: "Rápido", position: "DF",
          stats: { velocidade: 80, chute: 52, tecnica: 74, defesa: 79, espirito: 76 },
          power: { name: "Arrancada do Líbero", desc: "Sai jogando lá de trás numa corrida que ninguém acompanha.", manaCost: 35, bonus: 28 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Defesa também pode terminar em gol." }),
        player({ id: "ale-5", name: "Andi Pênalti-de-Ouro", number: 5, nationality: "Alemanha", flag: "🇩🇪", temperament: "Oportunista", position: "LAT",
          stats: { velocidade: 62, chute: 70, tecnica: 72, defesa: 76, espirito: 80 },
          power: { name: "Cobrança Fria", desc: "Na hora mais tensa, o pé não treme.", manaCost: 36, bonus: 28 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Pênalti decisivo? Chama a mim." }),
        player({ id: "ale-6", name: "Lothar Motorzão", number: 6, nationality: "Alemanha", flag: "🇩🇪", temperament: "Bruto", position: "MF",
          stats: { velocidade: 66, chute: 62, tecnica: 70, defesa: 66, espirito: 82 },
          power: { name: "Motor Incansável", desc: "Corre o jogo inteiro sem baixar o ritmo nem por um segundo.", manaCost: 39, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Eu não canso. Eu recarrego correndo." }),
        player({ id: "ale-7", name: "Toni Compasso", number: 7, nationality: "Alemanha", flag: "🇩🇪", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 58, chute: 58, tecnica: 89, defesa: 50, espirito: 78 },
          power: { name: "Passe Cirúrgico", desc: "Encontra o companheiro certo mesmo do outro lado do campo.", manaCost: 40, bonus: 30 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "Eu meço o passe em milímetros." }),
        player({ id: "ale-8", name: "Mesüt Raio-X", number: 8, nationality: "Alemanha", flag: "🇩🇪", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 64, chute: 55, tecnica: 87, defesa: 42, espirito: 75 },
          power: { name: "Visão de Raio-X", desc: "Enxerga o espaço vazio antes dele existir.", manaCost: 40, bonus: 30 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "Eu já vi esse passe na minha cabeça há três jogadas." }),
        player({ id: "ale-9", name: "Tommy Faro-Espacial", number: 9, nationality: "Alemanha", flag: "🇩🇪", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 78, chute: 80, tecnica: 72, defesa: 30, espirito: 72 },
          power: { name: "Faro de Espaço", desc: "Sempre está exatamente onde a defesa não imaginava.", manaCost: 48, bonus: 36 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Ninguém sabe explicar como eu cheguei ali. Nem eu." }),
        player({ id: "ale-10", name: "Miro Cambalhota", number: 10, nationality: "Alemanha", flag: "🇩🇪", temperament: "Rápido", position: "FW",
          stats: { velocidade: 82, chute: 84, tecnica: 70, defesa: 28, espirito: 70 },
          power: { name: "Voleio Acrobático", desc: "Termina a jogada com uma cambalhota e a bola no fundo da rede.", manaCost: 47, bonus: 35 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "Gol eu comemoro no ar." }),
        player({ id: "ale-11", name: "Gerdão Bombardeiro", number: 11, nationality: "Alemanha", flag: "🇩🇪", temperament: "Bruto", position: "FW",
          stats: { velocidade: 74, chute: 89, tecnica: 68, defesa: 26, espirito: 66 },
          power: { name: "Bombardeio na Área", desc: "Dentro da área pequena, ninguém finaliza mais rápido.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Área é meu território de caça." })
      ]
    },
    {
      id: "FRA", name: "França", shortName: "FRA", kit: "FFF · Azul Blues",
      colorVar: "franca", badge: "🇫🇷", assetPrefix: "FRANCA",
      players: [
        player({ id: "fra-1", name: "Fabinho Careca-da-Sorte", number: 1, nationality: "França", flag: "🇫🇷", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 56, chute: 12, tecnica: 50, defesa: 90, espirito: 84 },
          power: { name: "Escanteio Blindado", desc: "Não sai bola nenhuma perto da trave enquanto ele estiver ali.", manaCost: 46, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Careca dá sorte. Pergunta pra taça." }),
        player({ id: "fra-2", name: "Lilico Zaga-Surpresa", number: 2, nationality: "França", flag: "🇫🇷", temperament: "Oportunista", position: "LAT",
          stats: { velocidade: 76, chute: 58, tecnica: 66, defesa: 78, espirito: 74 },
          power: { name: "Gol Inesperado", desc: "Sobe pra área e marca justamente quando ninguém espera.", manaCost: 37, bonus: 29 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Defensor também pode decidir a partida." }),
        player({ id: "fra-3", name: "Marcel Rochedo", number: 3, nationality: "França", flag: "🇫🇷", temperament: "Bruto", position: "DF",
          stats: { velocidade: 64, chute: 38, tecnica: 62, defesa: 88, espirito: 80 },
          power: { name: "Muralha de Pedra", desc: "Um desarme tão sólido que parece bater numa rocha de verdade.", manaCost: 35, bonus: 28 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Ninguém quebra essa pedra." }),
        player({ id: "fra-4", name: "Laurentino Presidente", number: 4, nationality: "França", flag: "🇫🇷", temperament: "Cerebral", position: "DF",
          stats: { velocidade: 62, chute: 42, tecnica: 80, defesa: 83, espirito: 85 },
          power: { name: "Decreto Presidencial", desc: "Organiza a zaga inteira com autoridade absoluta.", manaCost: 34, bonus: 27 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Aqui quem manda na defesa sou eu." }),
        player({ id: "fra-5", name: "Bixente Judoca", number: 5, nationality: "França", flag: "🇫🇷", temperament: "Bruto", position: "LAT",
          stats: { velocidade: 70, chute: 40, tecnica: 64, defesa: 85, espirito: 78 },
          power: { name: "Golpe de Judô", desc: "Desarma o adversário com a precisão de uma faixa preta.", manaCost: 37, bonus: 29 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Categoria de peso não me assusta." }),
        player({ id: "fra-6", name: "N'Golinho Pulmão-de-Aço", number: 6, nationality: "França", flag: "🇫🇷", temperament: "Rápido", position: "MF",
          stats: { velocidade: 84, chute: 55, tecnica: 76, defesa: 82, espirito: 88 },
          power: { name: "Desarme Relâmpago", desc: "Recupera a bola tão rápido que parece estar em dois lugares ao mesmo tempo.", manaCost: 39, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Tem só um de mim. Mas parecem dois." }),
        player({ id: "fra-7", name: "Michel Batuta", number: 7, nationality: "França", flag: "🇫🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 60, chute: 80, tecnica: 88, defesa: 45, espirito: 82 },
          power: { name: "Falta Magistral", desc: "Rege a cobrança de falta como uma orquestra inteira.", manaCost: 41, bonus: 31 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "Eu não chuto a falta. Eu a componho." }),
        player({ id: "fra-8", name: "Yannick Malabarista", number: 8, nationality: "França", flag: "🇫🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 66, chute: 78, tecnica: 92, defesa: 46, espirito: 80 },
          power: { name: "Giro de Marselha", desc: "Um giro tão elegante que engana até quem está assistindo pela TV.", manaCost: 41, bonus: 31 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "A bola obedece antes de eu tocar nela." }),
        player({ id: "fra-9", name: "Kiki Vapor", number: 9, nationality: "França", flag: "🇫🇷", temperament: "Rápido", position: "FW",
          stats: { velocidade: 92, chute: 85, tecnica: 80, defesa: 24, espirito: 68 },
          power: { name: "Rajada de Vento", desc: "Acelera tão forte que vira só um borrão pra defesa.", manaCost: 47, bonus: 35 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Você piscou? Já era." }),
        player({ id: "fra-10", name: "Titi Estiloso", number: 10, nationality: "França", flag: "🇫🇷", temperament: "Cerebral", position: "FW",
          stats: { velocidade: 84, chute: 87, tecnica: 84, defesa: 26, espirito: 72 },
          power: { name: "Finalização Estilosa", desc: "Define com uma classe que faz o gol parecer fácil.", manaCost: 46, bonus: 34 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "Gol também pode ter estilo." }),
        player({ id: "fra-11", name: "Franckinho Requebro", number: 11, nationality: "França", flag: "🇫🇷", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 80, chute: 76, tecnica: 86, defesa: 28, espirito: 74 },
          power: { name: "Requebro Desconcertante", desc: "Um drible tão inesperado que o marcador cai sozinho.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Minha perna tem samba escondido." })
      ]
    },
    {
      id: "ARG", name: "Argentina", shortName: "ARG", kit: "AFA · Albiceleste",
      colorVar: "argentina", badge: "🇦🇷", assetPrefix: "ARGENTINA",
      players: [
        player({ id: "arg-1", name: "Baldo Pato-de-Ferro", number: 1, nationality: "Argentina", flag: "🇦🇷", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 52, chute: 11, tecnica: 46, defesa: 90, espirito: 84 },
          power: { name: "Voo do Pato", desc: "Um salto elástico que tira a bola do ângulo mais impossível.", manaCost: 47, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Bola no ângulo? Isso aqui é lagoa de pato." }),
        player({ id: "arg-2", name: "Xavier Trator-Eterno", number: 2, nationality: "Argentina", flag: "🇦🇷", temperament: "Cerebral", position: "LAT",
          stats: { velocidade: 70, chute: 42, tecnica: 76, defesa: 79, espirito: 85 },
          power: { name: "Corrida Sem Fim", desc: "Sobe e desce a lateral inteira como se o jogo tivesse acabado de começar.", manaCost: 36, bonus: 28 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Vinte anos correndo essa lateral. Ainda não cansei." }),
        player({ id: "arg-3", name: "Danilo Capitão-de-Ferro", number: 3, nationality: "Argentina", flag: "🇦🇷", temperament: "Bruto", position: "DF",
          stats: { velocidade: 60, chute: 55, tecnica: 62, defesa: 85, espirito: 90 },
          power: { name: "Comando Absoluto", desc: "Sobe pra área e resolve de cabeça como só um capitão resolve.", manaCost: 35, bonus: 28 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Time meu não recua a cabeça baixa." }),
        player({ id: "arg-4", name: "Beto Ratão", number: 4, nationality: "Argentina", flag: "🇦🇷", temperament: "Cerebral", position: "DF",
          stats: { velocidade: 68, chute: 40, tecnica: 68, defesa: 84, espirito: 78 },
          power: { name: "Faro de Roedor", desc: "Antecipa o passe antes mesmo dele sair do pé do rival.", manaCost: 34, bonus: 27 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Eu não corro atrás da bola. Eu já estou lá." }),
        player({ id: "arg-5", name: "Juanpi Braçal-de-Aço", number: 5, nationality: "Argentina", flag: "🇦🇷", temperament: "Rápido", position: "LAT",
          stats: { velocidade: 84, chute: 48, tecnica: 66, defesa: 74, espirito: 88 },
          power: { name: "Overlap Apaixonado", desc: "Explode pela lateral com o braçal balançando de tanta paixão.", manaCost: 37, bonus: 29 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Esse braçal pesa. Mas eu corro igual." }),
        player({ id: "arg-6", name: "Nando Calcanhar-de-Ouro", number: 6, nationality: "Argentina", flag: "🇦🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 58, chute: 62, tecnica: 90, defesa: 55, espirito: 82 },
          power: { name: "Calcanhar Sem Olhar", desc: "Um toque de calcanhar tão elegante que nem ele mesmo vê acontecer.", manaCost: 40, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Pra que olhar? Eu já sei onde ele está." }),
        player({ id: "arg-7", name: "Mário Matador-Melena", number: 7, nationality: "Argentina", flag: "🇦🇷", temperament: "Rápido", position: "MF",
          stats: { velocidade: 82, chute: 80, tecnica: 74, defesa: 46, espirito: 76 },
          power: { name: "Investida Setenta-e-Oito", desc: "Arranca do meio-campo com a cabeleira ao vento e não para mais.", manaCost: 39, bonus: 30 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "Corro até o cabelo cansar. E ele nunca cansa." }),
        player({ id: "arg-8", name: "Juanro Compasso-Lento", number: 8, nationality: "Argentina", flag: "🇦🇷", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 52, chute: 72, tecnica: 92, defesa: 42, espirito: 80 },
          power: { name: "Pausa Genial", desc: "Segura o tempo do jogo até todo mundo se mover errado.", manaCost: 41, bonus: 31 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "Pressa é coisa de quem não sabe jogar." }),
        player({ id: "arg-9", name: "Gabo Canhão-de-Fogo", number: 9, nationality: "Argentina", flag: "🇦🇷", temperament: "Bruto", position: "FW",
          stats: { velocidade: 78, chute: 91, tecnica: 72, defesa: 26, espirito: 74 },
          power: { name: "Fúria de Gol", desc: "Um chute tão forte que a rede pega fogo de verdade.", manaCost: 48, bonus: 36 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Quando eu bato, a comemoração já começou antes da bola entrar." }),
        player({ id: "arg-10", name: "Diego Mãozinha-de-Ouro", number: 10, nationality: "Argentina", flag: "🇦🇷", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 85, chute: 89, tecnica: 96, defesa: 30, espirito: 90 },
          power: { name: "Golpe de Gênio", desc: "Faz o impossível parecer óbvio — a mão ou o pé, não importa.", manaCost: 49, bonus: 37 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "Foi um pouco a cabeça e um pouco a mão de Deus." }),
        player({ id: "arg-11", name: "Leo Pulga-Atômica", number: 11, nationality: "Argentina", flag: "🇦🇷", temperament: "Rápido", position: "FW",
          stats: { velocidade: 90, chute: 88, tecnica: 94, defesa: 28, espirito: 72 },
          power: { name: "Explosão da Pulga", desc: "Um pulo de velocidade tão curto e certeiro que ninguém vê a saída.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Pequeno eu sou. Pequena é a chance de me pegar." })
      ]
    },
    {
      id: "ITA", name: "Itália", shortName: "ITA", kit: "FIGC · Azzurri",
      colorVar: "italia", badge: "🇮🇹", assetPrefix: "ITALIA",
      players: [
        player({ id: "ita-1", name: "Dino Reflexo-Eterno", number: 1, nationality: "Itália", flag: "🇮🇹", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 48, chute: 9, tecnica: 50, defesa: 91, espirito: 88 },
          power: { name: "Reflexo dos Quarenta", desc: "Um reflexo tão calibrado que nem a idade consegue atrasar.", manaCost: 47, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Idade é só um número. A bola que pergunte pro meu reflexo." }),
        player({ id: "ita-2", name: "Cláudio Sombra-de-Ferro", number: 2, nationality: "Itália", flag: "🇮🇹", temperament: "Bruto", position: "LAT",
          stats: { velocidade: 62, chute: 32, tecnica: 58, defesa: 88, espirito: 80 },
          power: { name: "Marcação Sufocante", desc: "Vira a sombra do rival e não deixa nem respirar.", manaCost: 36, bonus: 28 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Craque nenhum joga livre perto de mim." }),
        player({ id: "ita-3", name: "Paolinho Postura-Nobre", number: 3, nationality: "Itália", flag: "🇮🇹", temperament: "Cerebral", position: "DF",
          stats: { velocidade: 66, chute: 44, tecnica: 82, defesa: 86, espirito: 86 },
          power: { name: "Elegância Absoluta", desc: "Desarma sem nunca precisar sujar o calção.", manaCost: 35, bonus: 28 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Se eu preciso me jogar no chão, já errei antes." }),
        player({ id: "ita-4", name: "Franquinho Vontade-de-Ferro", number: 4, nationality: "Itália", flag: "🇮🇹", temperament: "Bruto", position: "DF",
          stats: { velocidade: 58, chute: 40, tecnica: 70, defesa: 87, espirito: 89 },
          power: { name: "Coração Blindado", desc: "Joga na raça mesmo machucado e ainda comanda a zaga inteira.", manaCost: 34, bonus: 27 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Dói? Dói. Eu jogo do mesmo jeito." }),
        player({ id: "ita-5", name: "Fabinho Gigante-Pequeno", number: 5, nationality: "Itália", flag: "🇮🇹", temperament: "Rápido", position: "LAT",
          stats: { velocidade: 80, chute: 36, tecnica: 68, defesa: 85, espirito: 84 },
          power: { name: "Salto do Pequeno Gigante", desc: "Sobe mais alto que qualquer atacante, do tamanho que for.", manaCost: 37, bonus: 29 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Tamanho não é documento. Bola de Ouro é." }),
        player({ id: "ita-6", name: "Andrezinho Arquiteto-Frio", number: 6, nationality: "Itália", flag: "🇮🇹", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 54, chute: 70, tecnica: 91, defesa: 50, espirito: 82 },
          power: { name: "Cucchiaio Glacial", desc: "Cobra com uma calma tão gelada que o goleiro já cai sozinho.", manaCost: 40, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Pênalti não se bate com o pé. Se bate com a cabeça fria." }),
        player({ id: "ita-7", name: "Sandrão Coração-Nerazzurro", number: 7, nationality: "Itália", flag: "🇮🇹", temperament: "Rápido", position: "MF",
          stats: { velocidade: 76, chute: 72, tecnica: 78, defesa: 48, espirito: 80 },
          power: { name: "Motor da Grande Inter", desc: "Corre o campo inteiro puxando o time nas costas.", manaCost: 39, bonus: 30 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "Enquanto eu correr, o time nunca para." }),
        player({ id: "ita-8", name: "Chiquinho Cucchiaio-de-Ouro", number: 8, nationality: "Itália", flag: "🇮🇹", temperament: "Oportunista", position: "MF",
          stats: { velocidade: 66, chute: 82, tecnica: 89, defesa: 40, espirito: 78 },
          power: { name: "Colherzinha Fatal", desc: "Uma cavadinha tão debochada que vira piada pro goleiro adversário.", manaCost: 41, bonus: 31 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "Pênalti de colher? Só se for pra rir depois." }),
        player({ id: "ita-9", name: "Beppe Estádio-Vivo", number: 9, nationality: "Itália", flag: "🇮🇹", temperament: "Rápido", position: "FW",
          stats: { velocidade: 86, chute: 84, tecnica: 76, defesa: 26, espirito: 68 },
          power: { name: "Lenda de Concreto", desc: "Joga tão bem que o próprio estádio um dia vai ganhar seu nome.", manaCost: 47, bonus: 35 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Um dia, meu nome vai estar na entrada do estádio." }),
        player({ id: "ita-10", name: "Betuccio Rabo-Divino", number: 10, nationality: "Itália", flag: "🇮🇹", temperament: "Cerebral", position: "FW",
          stats: { velocidade: 78, chute: 86, tecnica: 93, defesa: 28, espirito: 76 },
          power: { name: "Toque Divino", desc: "Um drible tão elegante que parece bênção, não talento.", manaCost: 46, bonus: 34 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "O rabo-de-cavalo balança, e a defesa já perdeu." }),
        player({ id: "ita-11", name: "Paulinho Redenção-de-Ouro", number: 11, nationality: "Itália", flag: "🇮🇹", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 79, chute: 89, tecnica: 74, defesa: 24, espirito: 70 },
          power: { name: "Redenção Total", desc: "Depois de qualquer queda, aparece pra decidir a Copa inteira sozinho.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Caí uma vez. Levantei pra ser artilheiro do mundo." })
      ]
    },
    {
      id: "ESP", name: "Espanha", shortName: "ESP", kit: "RFEF · Fúria Vermelha",
      colorVar: "espanha", badge: "🇪🇸", assetPrefix: "ESPANHA",
      players: [
        player({ id: "esp-1", name: "Iquinho Milagre-Santo", number: 1, nationality: "Espanha", flag: "🇪🇸", temperament: "Cerebral", position: "GK",
          stats: { velocidade: 54, chute: 10, tecnica: 48, defesa: 91, espirito: 87 },
          power: { name: "Milagre de San Iker", desc: "Uma defesa tão impossível que parece coisa de santo.", manaCost: 47, bonus: 35 },
          start: { row: 4, col: 0 }, assetKey: 1, quote: "Alguns chamam de sorte. Eu chamo de fé." }),
        player({ id: "esp-2", name: "Sergião Cabeçada-Salvadora", number: 2, nationality: "Espanha", flag: "🇪🇸", temperament: "Bruto", position: "LAT",
          stats: { velocidade: 66, chute: 58, tecnica: 62, defesa: 84, espirito: 86 },
          power: { name: "Cabeçada do Minuto 90", desc: "Aparece na área no momento exato pra salvar o time de cabeça.", manaCost: 37, bonus: 29 },
          start: { row: 1, col: 2 }, assetKey: 2, quote: "Minuto noventa e três é a minha hora favorita." }),
        player({ id: "esp-3", name: "Nando Coração-de-Ferro", number: 3, nationality: "Espanha", flag: "🇪🇸", temperament: "Cerebral", position: "DF",
          stats: { velocidade: 60, chute: 52, tecnica: 78, defesa: 85, espirito: 84 },
          power: { name: "Vontade de Ferro", desc: "Comanda a zaga com uma frieza forjada em aço.", manaCost: 34, bonus: 27 },
          start: { row: 3, col: 2 }, assetKey: 3, quote: "Meu sobrenome já diz tudo sobre minha marcação." }),
        player({ id: "esp-4", name: "Carlitos Bandana-Guerreira", number: 4, nationality: "Espanha", flag: "🇪🇸", temperament: "Bruto", position: "DF",
          stats: { velocidade: 64, chute: 38, tecnica: 60, defesa: 89, espirito: 92 },
          power: { name: "Grito de Guerra", desc: "Joga o corpo inteiro na bola como se fosse a última jogada da vida.", manaCost: 35, bonus: 28 },
          start: { row: 5, col: 2 }, assetKey: 4, quote: "Bandana amarrada, coração na luta." }),
        player({ id: "esp-5", name: "Jordizinho Alba-Relâmpago", number: 5, nationality: "Espanha", flag: "🇪🇸", temperament: "Rápido", position: "LAT",
          stats: { velocidade: 88, chute: 54, tecnica: 72, defesa: 76, espirito: 78 },
          power: { name: "Amanhecer Relâmpago", desc: "Dispara pela esquerda antes mesmo do sol nascer pra defesa.", manaCost: 37, bonus: 29 },
          start: { row: 7, col: 2 }, assetKey: 5, quote: "Onde tem espaço, eu já cheguei antes." }),
        player({ id: "esp-6", name: "Sergi Metrônomo-Silencioso", number: 6, nationality: "Espanha", flag: "🇪🇸", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 56, chute: 46, tecnica: 84, defesa: 68, espirito: 84 },
          power: { name: "Batida Perfeita", desc: "Controla o ritmo do jogo inteiro sem ninguém perceber como.", manaCost: 39, bonus: 30 },
          start: { row: 4, col: 4 }, assetKey: 6, quote: "Ninguém vê o que eu faço. Só sente falta quando eu não faço." }),
        player({ id: "esp-7", name: "Xavinho Bússola-de-Ouro", number: 7, nationality: "Espanha", flag: "🇪🇸", temperament: "Cerebral", position: "MF",
          stats: { velocidade: 58, chute: 60, tecnica: 93, defesa: 48, espirito: 82 },
          power: { name: "Norte Verdadeiro", desc: "Aponta o passe certo antes de qualquer bússola existir.", manaCost: 40, bonus: 30 },
          start: { row: 2, col: 4 }, assetKey: 7, quote: "A bola sempre sabe pra onde ir. Eu só aponto o caminho." }),
        player({ id: "esp-8", name: "Andresito Gol-Eterno", number: 8, nationality: "Espanha", flag: "🇪🇸", temperament: "Oportunista", position: "MF",
          stats: { velocidade: 68, chute: 76, tecnica: 90, defesa: 44, espirito: 80 },
          power: { name: "Gol da Vida Inteira", desc: "Aparece do nada no momento mais importante da história.", manaCost: 41, bonus: 31 },
          start: { row: 6, col: 4 }, assetKey: 8, quote: "Esse gol vai ficar pra sempre. E eu sabia disso." }),
        player({ id: "esp-9", name: "Fer Menino-Relâmpago", number: 9, nationality: "Espanha", flag: "🇪🇸", temperament: "Rápido", position: "FW",
          stats: { velocidade: 89, chute: 85, tecnica: 76, defesa: 24, espirito: 66 },
          power: { name: "Disparada do Menino", desc: "Sai do ombro do zagueiro numa explosão de velocidade pura.", manaCost: 47, bonus: 35 },
          start: { row: 2, col: 5 }, assetKey: 9, quote: "Eles nem viram o menino passar." }),
        player({ id: "esp-10", name: "Raulzinho Dedo-nos-Lábios", number: 10, nationality: "Espanha", flag: "🇪🇸", temperament: "Cerebral", position: "FW",
          stats: { velocidade: 76, chute: 87, tecnica: 85, defesa: 26, espirito: 78 },
          power: { name: "Silêncio de Ouro", desc: "Marca e comemora com um gesto tão frio que a torcida rival se cala.", manaCost: 46, bonus: 34 },
          start: { row: 4, col: 5 }, assetKey: 10, quote: "Psiu. Aqui quem fala sou eu, com os pés." }),
        player({ id: "esp-11", name: "Davizinho Artilheiro-Mor", number: 11, nationality: "Espanha", flag: "🇪🇸", temperament: "Oportunista", position: "FW",
          stats: { velocidade: 82, chute: 88, tecnica: 80, defesa: 25, espirito: 72 },
          power: { name: "Instinto Artilheiro", desc: "Sempre encontra o canto certo, mesmo sem espaço nenhum.", manaCost: 48, bonus: 36 },
          start: { row: 6, col: 5 }, assetKey: 11, quote: "Artilheiro não erra o alvo. Encontra outro ângulo." })
      ]
    }
  ];

  return { POSITIONS: POSITIONS, TEMPERAMENTS: TEMPERAMENTS, STATS: STATS, TEAMS: TEAMS };

})();
